version: "3.8"

services:
  
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - $PWD/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: ishmamruhan/user_service_spring_crud
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      spring.datasource.url : jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
      spring.datasource.username : $MYSQLDB_USER
      spring.datasource.password : $MYSQLDB_ROOT_PASSWORD
      spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL8Dialect
      spring.jpa.hibernate.ddl-auto : update
